export { default as LogoFull } from './LogoFull'
export { default as LogoText } from './LogoText'
export { default as Burguer } from './Burguer'
export { default as LogoSquare } from './LogoSquare'
export { HugeTitleAbout, HugeTitleContact, HugeTitleExplore } from './HugeTitle'
